server.port=9090
spring.application.name=gateway-service

# Shows which route matched the request
logging.level.org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator=INFO
logging.level.org.springframework.cloud.gateway=TRACE

# Your custom logs
logging.level.com.Wealth.config=DEBUG

# Route 0: Auth
# Disable the default 'Path' shorthand and use the full definition
# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
#logging.level.org.springframework.cloud.gateway=TRACE
#logging.level.org.springframework.http.server.reactive=DEBUG
#logging.level.com.translink=DEBUG
# Actuator Fix (To stop the 404 on /actuator)
management.endpoints.web.exposure.include=gateway,health,info
management.endpoint.gateway.enabled=true
management.info.gateway.enabled=true